# Removal of TSCA degradates that are not TSCA8a7

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import openpyxl
from rdkit.Chem.Draw import IPythonConsole, MolsToGridImage

#Show mols in dataframes
from rdkit.Chem import PandasTools
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage
from IPython.core.display import HTML
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors
from rdkit.Chem import PandasTools
from rdkit.Chem import AllChem
from rdkit.Chem import rdDepictor
from rdkit.Chem.Fingerprints import FingerprintMols
from rdkit import DataStructs
import os

In [2]:
TOP = os.getcwd().replace('notebooks', '')
raw_dir = TOP + 'data/raw/'
interim_dir = TOP + 'data/interim/'
external_dir = TOP + 'data/external/'
figures_dir = TOP + 'reports/figures/'

In [3]:
data_toAW = pd.read_csv(external_dir+'pfas_tsca_degradation.csv')

In [10]:
data_toAW.columns = ['GRACE_ID', 'INCHI_KEY', 'ID', 'SMILES', 'chain_length']

In [13]:
data_toAW[data_toAW['GRACE_ID'] ==38]

GRACE_ID                    INCHI_KEY                     ID  \
26        38  AFTSHZRGGNMLHC-UHFFFAOYSA-N  ['DTXSID6021377_m_1']   

             SMILES  chain_length  
26  FC(F)C(F)(Cl)Cl             1

In [5]:
AW_returned = pd.read_excel(external_dir+'NONPFAS structures.xlsx')

In [16]:
ids_to_del = AW_returned['GRACE_ID'].tolist()

In [34]:
data_toAW[data_toAW['GRACE_ID'].isin(ids_to_del)].to_csv(interim_dir+'data_todel.csv')

In [32]:
ids_to_rm = data_toAW[data_toAW['GRACE_ID'].isin(ids_to_del)]['INCHI_KEY'].tolist()

In [25]:
universe = pd.read_excel(interim_dir+'universe_020524.xlsx', index_col = [0])

In [35]:
universe[universe['dtxsid'].isin(ids_to_rm)].to_csv(interim_dir+'data_todel_cf.csv')

In [39]:
universe1 = universe[~universe['dtxsid'].isin(ids_to_rm)]

In [44]:
universe1[(universe1['ID'].notnull()) & (universe1['ID'] != 'matches_tsca_degradate')].shape

(2484, 168)

In [45]:
universe1.shape

(15538, 168)

The landscape comprises 15,538 substances of which these contain 2484 TSCA degradates.

In [48]:
15538-2484

13054

In [47]:
writer = pd.ExcelWriter(interim_dir+'universe_060625.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.

universe1.to_excel(writer)

writer.close()
